// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExampleEndpoints.proto

package coprocessor.endpoint;

public final class ExampleEndpoints {
  private ExampleEndpoints() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ColumnCountRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ColumnCountRequest}
   */
  public static final class ColumnCountRequest extends
      com.google.protobuf.GeneratedMessage
      implements ColumnCountRequestOrBuilder {
    // Use ColumnCountRequest.newBuilder() to construct.
    private ColumnCountRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ColumnCountRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ColumnCountRequest defaultInstance;
    public static ColumnCountRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ColumnCountRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ColumnCountRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.class, coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ColumnCountRequest> PARSER =
        new com.google.protobuf.AbstractParser<ColumnCountRequest>() {
      public ColumnCountRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ColumnCountRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ColumnCountRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ColumnCountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements coprocessor.endpoint.ExampleEndpoints.ColumnCountRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.class, coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.Builder.class);
      }

      // Construct using coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountRequest_descriptor;
      }

      public coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest getDefaultInstanceForType() {
        return coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.getDefaultInstance();
      }

      public coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest build() {
        coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest buildPartial() {
        coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest result = new coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest) {
          return mergeFrom((coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest other) {
        if (other == coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ColumnCountRequest)
    }

    static {
      defaultInstance = new ColumnCountRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ColumnCountRequest)
  }

  public interface ColumnCountResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 count = 1 [default = 0];
    /**
     * <code>required int64 count = 1 [default = 0];</code>
     */
    boolean hasCount();
    /**
     * <code>required int64 count = 1 [default = 0];</code>
     */
    long getCount();
  }
  /**
   * Protobuf type {@code ColumnCountResponse}
   */
  public static final class ColumnCountResponse extends
      com.google.protobuf.GeneratedMessage
      implements ColumnCountResponseOrBuilder {
    // Use ColumnCountResponse.newBuilder() to construct.
    private ColumnCountResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ColumnCountResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ColumnCountResponse defaultInstance;
    public static ColumnCountResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ColumnCountResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ColumnCountResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              count_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.class, coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ColumnCountResponse> PARSER =
        new com.google.protobuf.AbstractParser<ColumnCountResponse>() {
      public ColumnCountResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ColumnCountResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ColumnCountResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 count = 1 [default = 0];
    public static final int COUNT_FIELD_NUMBER = 1;
    private long count_;
    /**
     * <code>required int64 count = 1 [default = 0];</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 count = 1 [default = 0];</code>
     */
    public long getCount() {
      return count_;
    }

    private void initFields() {
      count_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ColumnCountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements coprocessor.endpoint.ExampleEndpoints.ColumnCountResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.class, coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.Builder.class);
      }

      // Construct using coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coprocessor.endpoint.ExampleEndpoints.internal_static_ColumnCountResponse_descriptor;
      }

      public coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse getDefaultInstanceForType() {
        return coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.getDefaultInstance();
      }

      public coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse build() {
        coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse buildPartial() {
        coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse result = new coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse) {
          return mergeFrom((coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse other) {
        if (other == coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 count = 1 [default = 0];
      private long count_ ;
      /**
       * <code>required int64 count = 1 [default = 0];</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 count = 1 [default = 0];</code>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>required int64 count = 1 [default = 0];</code>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000001;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 count = 1 [default = 0];</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ColumnCountResponse)
    }

    static {
      defaultInstance = new ColumnCountResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ColumnCountResponse)
  }

  /**
   * Protobuf service {@code ColumnCountService}
   */
  public static abstract class ColumnCountService
      implements com.google.protobuf.Service {
    protected ColumnCountService() {}

    public interface Interface {
      /**
       * <code>rpc getColumnCount(.ColumnCountRequest) returns (.ColumnCountResponse);</code>
       */
      public abstract void getColumnCount(
          com.google.protobuf.RpcController controller,
          coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest request,
          com.google.protobuf.RpcCallback<coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ColumnCountService() {
        @java.lang.Override
        public  void getColumnCount(
            com.google.protobuf.RpcController controller,
            coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest request,
            com.google.protobuf.RpcCallback<coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse> done) {
          impl.getColumnCount(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getColumnCount(controller, (coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getColumnCount(.ColumnCountRequest) returns (.ColumnCountResponse);</code>
     */
    public abstract void getColumnCount(
        com.google.protobuf.RpcController controller,
        coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest request,
        com.google.protobuf.RpcCallback<coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return coprocessor.endpoint.ExampleEndpoints.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getColumnCount(controller, (coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest)request,
            com.google.protobuf.RpcUtil.<coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends coprocessor.endpoint.ExampleEndpoints.ColumnCountService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getColumnCount(
          com.google.protobuf.RpcController controller,
          coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest request,
          com.google.protobuf.RpcCallback<coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.class,
            coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse getColumnCount(
          com.google.protobuf.RpcController controller,
          coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse getColumnCount(
          com.google.protobuf.RpcController controller,
          coprocessor.endpoint.ExampleEndpoints.ColumnCountRequest request)
          throws com.google.protobuf.ServiceException {
        return (coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          coprocessor.endpoint.ExampleEndpoints.ColumnCountResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ColumnCountService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ColumnCountRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ColumnCountRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ColumnCountResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ColumnCountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ExampleEndpoints.proto\"\024\n\022ColumnCountR" +
      "equest\"\'\n\023ColumnCountResponse\022\020\n\005count\030\001" +
      " \002(\003:\00102Q\n\022ColumnCountService\022;\n\016getColu" +
      "mnCount\022\023.ColumnCountRequest\032\024.ColumnCou" +
      "ntResponseB+\n\024coprocessor.endpointB\020Exam" +
      "pleEndpoints\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ColumnCountRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ColumnCountRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ColumnCountRequest_descriptor,
              new java.lang.String[] { });
          internal_static_ColumnCountResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ColumnCountResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ColumnCountResponse_descriptor,
              new java.lang.String[] { "Count", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}